# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stack < Formula
  desc "Stacked PR CLI for GitHub built with Go and Charm"
  homepage "https://github.com/hack-dance/stack"
  version "0.1.2"

  depends_on "gh"
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hack-dance/stack/releases/download/v0.1.2/stack_0.1.2_darwin_amd64.tar.gz"
      sha256 "e6ecc22b88f79739e1956273c5be06002ce79e517468d5d835c7866e6127c412"

      define_method(:install) do
        bin.install "stack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hack-dance/stack/releases/download/v0.1.2/stack_0.1.2_darwin_arm64.tar.gz"
      sha256 "7ede4df02ca53e7fe84b614eaadafcce05ca513fa3ce69009b69ce196764ed67"

      define_method(:install) do
        bin.install "stack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hack-dance/stack/releases/download/v0.1.2/stack_0.1.2_linux_amd64.tar.gz"
      sha256 "c9084e6da9880b5282f5c1c532a65bc76788de5f6fe92e7e229827800ea460bc"
      define_method(:install) do
        bin.install "stack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hack-dance/stack/releases/download/v0.1.2/stack_0.1.2_linux_arm64.tar.gz"
      sha256 "5ec313187fa05af7a0e5e0d616e0ecac0cd8511935136f39ecc954a160fb55ed"
      define_method(:install) do
        bin.install "stack"
      end
    end
  end

  test do
    system "#{bin}/stack", "version"
  end
end
