# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stack < Formula
  desc "Stacked PR CLI for GitHub built with Go and Charm"
  homepage "https://github.com/hack-dance/stack"
  version "0.1.1"

  depends_on "gh"
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hack-dance/stack/releases/download/v0.1.1/stack_0.1.1_darwin_amd64.tar.gz"
      sha256 "fcfd498cc3fd99a4dd0e0536b247ccd147034edb9ab418438ddbd06d605542ff"

      define_method(:install) do
        bin.install "stack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hack-dance/stack/releases/download/v0.1.1/stack_0.1.1_darwin_arm64.tar.gz"
      sha256 "7850bb86e4d8d67493cacb9e915b517491bae6933ea57068573815b04f7950d3"

      define_method(:install) do
        bin.install "stack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hack-dance/stack/releases/download/v0.1.1/stack_0.1.1_linux_amd64.tar.gz"
      sha256 "be31420a37a0fa39146f387e5abd5326a24204cbfce45ae60fb99e34d273b186"
      define_method(:install) do
        bin.install "stack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hack-dance/stack/releases/download/v0.1.1/stack_0.1.1_linux_arm64.tar.gz"
      sha256 "81189fedfeecc3e17c0e150184afefc54aee127d451df63ecb2d33f499aeb0f6"
      define_method(:install) do
        bin.install "stack"
      end
    end
  end

  test do
    system "#{bin}/stack", "version"
  end
end
